raw <- subset(read.table("household_power_consumption.txt", header = TRUE, sep = ";", dec = "."), Date== "1/2/2007" | Date == "2/2/2007")
active_power <- as.numeric(as.character(raw$Global_active_power))
hist(active_power, col='red', main="Global Active Power", xlab = "Global Active Power (kilowatts)")
dev.copy(png, "figure/plot1.png", width = 480, height = 480)
dev.off()