png(filename = "figure/plot3.png",width = 480,height = 480)
raw <- subset(read.table("household_power_consumption.txt", header = TRUE, sep = ";", dec = "."), Date== "1/2/2007" | Date == "2/2/2007")
raw$Global_active_power <- as.numeric(as.character(raw$Global_active_power))
raw$NewTime <- as.POSIXct(strptime(paste(raw$Date, raw$Time, sep=" "), format = "%e/%m/%Y %H:%M:%S"))
Sys.setlocale("LC_TIME", "English")
with(raw,plot(NewTime,as.numeric(as.character(Sub_metering_1)),type="l", xlab="",ylab="Energy sub metering", ylim=c(0, 38)))
lines(raw$NewTime, as.numeric(as.character(raw$Sub_metering_2)), col="red")
lines(raw$NewTime, as.numeric(as.character(raw$Sub_metering_3)), col="blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = 1, cex=0.9)
dev.off()